icey/src/main/java/com/project/icey/app/controller/BalanceGameController.java, icey/src/main/java/com/project/icey/app/controller/LoginController.java, icey/src/main/java/com/project/icey/app/controller/NotificationController.java, icey/src/main/java/com/project/icey/app/domain/NotificationEntity.java, icey/src/main/java/com/project/icey/app/domain/NotificationType.java, icey/src/main/java/com/project/icey/app/dto/BalanceGameResultDto.java, icey/src/main/java/com/project/icey/app/dto/LoginRequestDto.java, icey/src/main/java/com/project/icey/app/dto/Notification.java, icey/src/main/java/com/project/icey/app/repository/BalanceGameRepository.java, icey/src/main/java/com/project/icey/app/repository/BalanceGameVoteRepository.java, icey/src/main/java/com/project/icey/app/repository/EmitterRepository.java, icey/src/main/java/com/project/icey/app/repository/NotificationRepository.java, icey/src/main/java/com/project/icey/app/service/BalanceGameService.java, icey/src/main/java/com/project/icey/app/service/NotificationService.java, icey/src/main/java/com/project/icey/app/service/SseEmitterService.java, icey/src/main/java/com/project/icey/global/config/SecurityConfig.java, icey/src/main/java/com/project/icey/global/config/WebConfig.java, icey/src/main/java/com/project/icey/global/exception/InvalidTokenException.java, icey/src/main/java/com/project/icey/global/exception/model/GlobalExceptionHandler.java, icey/src/main/resources/static/login.html, icey/src/main/resources/static/sse-test.html
closed #24 
- SSE 구독: GET /api/notification/subscribe?token=<JWT>
- Content-Type: text/event-stream
- 토큰 유효성 검사는 서버에서 처리되며, 사용자 ID는 JWT로부터 추출합니다.
- 클라이언트는 EventSource를 사용하여 이 URL로 연결하면 실시간 알림을 받을 수 있습니다.
- 서버는 "sse" 이벤트 이름으로 JSON 알림 데이터를 전송합니다.
- 안 읽은 알림 조회: GET /api/notification/unread
- Authorization: Bearer <accessToken> 헤더 필요
- 응답: JSON 배열 형태의 알림 목록
- /login.html 로 접속하여 이메일 입력 후 로그인
- /sse-test.html 로 넘어가면 실시간 알림 확인 가능
```java
public enum NotificationType {
LETTER,             // 쪽지 알림
TEAM_EXPIRATION,     // 팀 유효기간 알림
APPOINTMENT_CREATED, // 약속 잡기 생성 알림
APPOINTMENT_COMPLETED, // 약속 완료 알림
NEW_MEMO,            // 신규 메모 알림
BALANCE_GAME_CREATED, // 밸런스 게임 생성 알림
SYSTEM_ALERT    // 시스템 알림
}
notificationService.sendNotification(
userId, …
```
=> feat: Notification

icey/src/main/java/com/project/icey/app/controller/NotificationController.java, icey/src/main/java/com/project/icey/app/service/BalanceGameService.java, icey/src/main/java/com/project/icey/app/service/SmallTalkService.java
closed #31 
- 스몰톡 AI 생성 질문 수정 안되도록 
- 밸런스 게임 프롬포트 수정
밸런스 게임 질문 예시............
=> Refactor: small talk, balance game 기능 점검

cloudbuild.yaml
=> Depoly: update cloudbuild.yaml

icey/Dockerfile
=> Depoly: update dockerfile

cloudbuild.yaml, icey/Dockerfile, icey/src/main/resources/application.yml
closed #38
- cloudbuild 환경변수 설정
=> Depoly: cloudbuild.yaml env update

icey/src/main/java/com/project/icey/global/config/WebConfig.java
closed #38 
- https 허용을 위한 webconfig 추가
- 로컬 실행 시 주석처리 필요
=> Depoly: WebConfig update

icey/src/main/java/com/project/icey/global/config/SwaggerConfig.java
closed #38 
- swagger config 배포 서버 추가
=> Depoly: swagger config update

icey/src/main/java/com/project/icey/app/controller/CardController.java, icey/src/main/java/com/project/icey/app/dto/CardRequest.java
closed #58 
@NotBlank 추가 및 컨트롤러에서 RequestBody 와 함께 Valid 추가(명함 생성 및 수정)
혹시 무조건 막는 게 아닌 다른 방법 원하시면 추후 수정하기
=> fix: 카드 정보 공백 불가 설정

icey/src/main/java/com/project/icey/app/dto/TeamDetailResponse.java, icey/src/main/java/com/project/icey/app/service/TeamService.java, icey/src/main/java/com/project/icey/global/config/WebConfig.java
closed #
1. 팀 상세 조회시 생성날짜 포함하여 반환
-----
(임시) cors 설정에 백엔드 로컬도 연결해두었습니다! 그쪽에 더미가 많아서 일단 설정해두었습니다!
프론트 배포전이라 프론트 로컬도 cors 설정에 넣어두었습니다!
=> Fix/teampage #62

icey/src/main/resources/application.yml
closed #
- 소셜 로그인 base url 업데이트 HOST->FRONTEND_BASE_URL
=> fix: social login base url update

icey/src/main/java/com/project/icey/app/service/TeamService.java, icey/src/main/resources/application.yml
closed #
카드 서비스 ensureMyCard를 TeamService에 연결
=> Chore: Card의 ensureMyCard를 teamservice에 연결하여 자동 명함 설정

icey/src/main/java/com/project/icey/oauth2/CustomOAuth2SuccessHandler.java, icey/src/main/resources/application.yml
closed #
- body 말고 쿼리스트링으로 토큰 전달
=> fix: social login redirect url update

icey/src/main/java/com/project/icey/app/controller/NotificationController.java
=> fix: 인코딩 문제 해결

icey/src/main/java/com/project/icey/app/controller/TeamController.java, icey/src/main/java/com/project/icey/app/service/TeamService.java
closed #
Chore: 팀 가입 성공시 teamId 반환
=> Chore: 팀 가입 성공시 teamId 반환

icey/src/main/java/com/project/icey/global/config/WebConfig.java
=> fix: cors 문제 해결

icey/src/main/java/com/project/icey/app/dto/CardRequest.java
closed #95 
request 에서 프로필색 아예 주석처리하고 백에서만 프로필색 관리하게 두기
=> fix: 리퀘스트에서 프로필색 삭제(연동 문제 해결 시도1)

icey/src/main/java/com/project/icey/app/controller/LoginController.java, icey/src/main/java/com/project/icey/global/config/SecurityConfig.java, icey/src/main/java/com/project/icey/oauth2/CustomOAuth2SuccessHandler.java
closed #
- 파라미터에 리프레시토큰 포함
- /api/refresh에서 다시 어세스토큰 발급
=> fix: 로그인 시 리프레시 토큰 전달

icey/src/main/java/com/project/icey/global/security/TokenService.java, icey/src/main/java/com/project/icey/oauth2/CustomOAuth2SuccessHandler.java
closed #
- refresh token에 사용자 이메일값 추가
=> fix: refresh token claim update

icey/src/main/java/com/project/icey/app/dto/MemoResponse.java, icey/src/main/java/com/project/icey/app/service/MemoService.java
closed #101 
메모 response 에 boolean mine 추가& 서비스와 todto 에서 viewerId 랑 authorId 를 비교
=> fix: 메모 response 에 boolean mine 추가

icey/src/main/java/com/project/icey/app/controller/BalanceGameController.java, icey/src/main/java/com/project/icey/app/dto/BalanceGameResultDto.java, icey/src/main/java/com/project/icey/app/repository/BalanceGameVoteRepository.java, icey/src/main/java/com/project/icey/app/service/BalanceGameService.java
closed #
```java
{
"status": 200,
"success": true,
"message": "게시글 조회가 완료되었습니다.",
"data": [
{
"id": 5,
"option1": "칼퇴",
"option1Count": 1,
"option2": "월급루팡",
"option2Count": 0,
"totalVotes": 1,
"createdAt": "2025-07-28T19:23:26.839491",
"userSelectedOption": 1
},
{
"id": 6,
"option1": "올림픽대로",
"option1Count": 0,
"option2": "강변북로",
"option2Count": 0,
"totalVotes": 0,
"createdAt": "2025-07-28T19:23:30.828156",
"userSelectedOption": null
}
]
}
```
로 결과 반환하도록
=> fix: balance game result dto add  createdAt

icey/src/main/java/com/project/icey/app/domain/AccessoryType.java, icey/src/main/java/com/project/icey/app/service/CardService.java
closed #
accessory type enum  한영 변환
=> Fix/card accessory type enum  한영 변환

icey/src/main/java/com/project/icey/app/dto/LikeUser.java, icey/src/main/java/com/project/icey/app/dto/MemoResponse.java, icey/src/main/java/com/project/icey/app/service/MemoService.java
=> [fix]: 메모 반응한 유저들 악세사리 정보도 반환하게 변경

icey/src/main/java/com/project/icey/app/service/SmallTalkService.java
=> fix: add api

icey/src/main/java/com/project/icey/app/domain/SmallTalk.java, icey/src/main/java/com/project/icey/app/service/SmallTalkService.java
=> fix: small talk swap api 수정

icey/src/main/java/com/project/icey/app/domain/SmallTalk.java
=> fix: question type enum

icey/src/main/java/com/project/icey/app/service/TeamService.java
=> fix: 팀 생성과 동시에 첫 메모 추가(팀장이 만든 걸로 처리해서 수정 삭제 권한도 팀장이 가짐)
